{{- $root := . -}}
{{- range $driver := .Values.drivers -}}
{{- if hasSuffix  "cephfs.csi.ceph.com" $driver.name }}
{{- $normalizedDriverName := include "normalizeDriverName" $driver.name }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $normalizedDriverName }}-ctrlplugin-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $normalizedDriverName }}-ctrlplugin-r
subjects:
- kind: ServiceAccount
  name: {{ $normalizedDriverName }}-ctrlplugin-sa
  namespace: {{ $root.Release.Namespace }}
{{- end }}
{{- end }}
