{{- $root := . -}}
{{- range $secret := .Values.secrets }}
{{- if $secret.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $secret.namespace | default $root.Release.Namespace }}
  labels:
    {{- include "ceph-csi-drivers.labels" $root | nindent 4 }}
    {{- with $secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
{{- with $secret.stringData }}
stringData:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
