{{- $root := . -}}
{{- range $driver := .Values.drivers -}}
{{- if  $driver.enabled }}
{{- $normalizedDriverName := include "normalizeDriverName" $driver.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $normalizedDriverName }}-ctrlplugin-sa
  namespace: {{ $root.Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $normalizedDriverName }}-nodeplugin-sa
  namespace: {{ $root.Release.Namespace }}
{{- end }}
{{- end }}
