{{- $root := . -}}
{{- range $driver := .Values.drivers -}}
{{- if  $driver.enabled }}
{{- $normalizedDriverName := include "normalizeDriverName" $driver.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $normalizedDriverName }}-ctrlplugin-sa
  namespace: {{ $root.Release.Namespace }}
{{- if gt (len $root.Values.imagePullSecrets) 0 }}
imagePullSecrets:
{{- range $pullSecret := $root.Values.imagePullSecrets }}
  - name: {{ $pullSecret }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $normalizedDriverName }}-nodeplugin-sa
  namespace: {{ $root.Release.Namespace }}
{{- if gt (len $root.Values.imagePullSecrets) 0 }}
imagePullSecrets:
{{- range $pullSecret := $root.Values.imagePullSecrets }}
  - name: {{ $pullSecret }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
