{{- if .Capabilities.APIVersions.Has "snapshot.storage.k8s.io/v1" }}
{{- $root := . -}}
{{- range $driverName, $driver := .Values.drivers -}}
{{- if $driver.enabled }}
{{- range $class := $driver.volumeSnapshotClasses }}
{{- if $class.name }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ $class.name }}
  labels:
    {{- include "ceph-csi-drivers.labels" $root | nindent 4 }}
    {{- with $class.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or $class.isDefault $class.annotations }}
  annotations:
    {{- if $class.isDefault }}
    snapshot.storage.kubernetes.io/is-default-class: "true"
    {{- end }}
    {{- with $class.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
driver: {{ $driver.name }}
deletionPolicy: {{ required "volumeSnapshotClasses[].deletionPolicy is required" $class.deletionPolicy }}
{{- if or $class.snapshotterSecretName $class.parameters }}
parameters:
  {{- if $class.snapshotterSecretName }}
  {{- if not (hasKey ($class.parameters | default dict) "csi.storage.k8s.io/snapshotter-secret-name") }}
  csi.storage.k8s.io/snapshotter-secret-name: {{ $class.snapshotterSecretName }}
  csi.storage.k8s.io/snapshotter-secret-namespace: {{ $class.snapshotterSecretNamespace | default $root.Release.Namespace }}
  {{- end }}
  {{- end }}
  {{- range $key, $value := $class.parameters }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
