version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - govet
    - gosec
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused

  exclusions:
    # don't exclude the default set of lint
    presets: []
    # restore some of the defaults
    # (fill in the rest as needed)
    rules:
      - path: "api/*"
        linters:
          - lll
      - path: "internal/*"
        linters:
          - dupl
          - lll

formatters:
  enable:
    - gofmt
    - goimports
