kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-rbd-ctrlplugin-role
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: ["csiaddons.openshift.io"]
    resources: ["csiaddonsnodes"]
    verbs: ["create"]
