# https://github.com/red-hat-storage/ocs-client-operator/issues/26
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cephfs-nodeplugin-cr
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
