apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-manager-role
  labels:
  {{- include "ceph-csi-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cbt.storage.k8s.io
  resources:
  - snapshotmetadataservices
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - csi.ceph.io
  resources:
  - cephconnections
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - csi.ceph.io
  resources:
  - clientprofilemappings
  - clientprofiles
  - drivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.ceph.io
  resources:
  - clientprofilemappings/finalizers
  - clientprofiles/finalizers
  - drivers/finalizers
  verbs:
  - update
- apiGroups:
  - csi.ceph.io
  resources:
  - clientprofilemappings/status
  - clientprofiles/status
  - drivers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - csi.ceph.io
  resources:
  - operatorconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "ceph-csi-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "ceph-csi-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "ceph-csi-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
