apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-ceph-csi-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ceph-csi-operator.labels" . | nindent 4 }}
spec:
  # Deny all ingress — no exposed ports.
  # Allow open egress for API server access.
  egress:
  - {}
  podSelector:
    matchLabels:
      control-plane: ceph-csi-op-controller-manager
  policyTypes:
  - Ingress
  - Egress
