apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-rbd-ctrlplugin-r
  labels:
  {{- include "ceph-csi-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - csiaddonsnodes
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  - daemonsets/finalizers
  verbs:
  - update
