apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-rbd-ctrlplugin-crb
  labels:
  {{- include "ceph-csi-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "ceph-csi-operator.fullname" . }}-rbd-ctrlplugin-cr'
subjects:
- kind: ServiceAccount
  name: '{{ include "ceph-csi-operator.fullname" . }}-rbd-ctrlplugin-sa'
  namespace: '{{ .Release.Namespace }}'
