{{- if .Values.openshift.enabled }}
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-scc
  labels:
    {{- include "ceph-csi-operator.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: >-
      SecurityContextConstraints for Ceph CSI drivers to enable privileged operations
      required for CSI functionality including host access and volume management.
# CSI daemonset pod needs to run as privileged
allowPrivilegedContainer: true
# CSI daemonset pod needs hostnetworking
allowHostNetwork: true
# CSI daemonset pod needs host ports for CSI addons
allowHostPorts: true
# Set for RBD plugin pod
allowHostPID: true
# Required for multus and encryption
allowHostIPC: true
# Allow host path volumes
allowHostDirVolumePlugin: true
# SYS_ADMIN is needed for rbd to execute rbd map command
allowedCapabilities:
  - SYS_ADMIN
# Run as any user
runAsUser:
  type: RunAsAny
# SELinux context
seLinuxContext:
  type: RunAsAny
# FSGroup
fsGroup:
  type: RunAsAny
# Supplemental groups
supplementalGroups:
  type: RunAsAny
# Containers write to root filesystem
readOnlyRootFilesystem: false
# Allowed volume types
volumes:
  - hostPath
  - configMap
  - emptyDir
  - projected
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-scc-user
  labels:
    {{- include "ceph-csi-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - {{ include "ceph-csi-operator.fullname" . }}-scc
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-rbd-ctrlplugin-scc
  labels:
    {{- include "ceph-csi-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ceph-csi-operator.fullname" . }}-scc-user
subjects:
  - kind: ServiceAccount
    name: {{ include "ceph-csi-operator.fullname" . }}-rbd-ctrlplugin-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-rbd-nodeplugin-scc
  labels:
    {{- include "ceph-csi-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ceph-csi-operator.fullname" . }}-scc-user
subjects:
  - kind: ServiceAccount
    name: {{ include "ceph-csi-operator.fullname" . }}-rbd-nodeplugin-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-cephfs-ctrlplugin-scc
  labels:
    {{- include "ceph-csi-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ceph-csi-operator.fullname" . }}-scc-user
subjects:
  - kind: ServiceAccount
    name: {{ include "ceph-csi-operator.fullname" . }}-cephfs-ctrlplugin-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-cephfs-nodeplugin-scc
  labels:
    {{- include "ceph-csi-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ceph-csi-operator.fullname" . }}-scc-user
subjects:
  - kind: ServiceAccount
    name: {{ include "ceph-csi-operator.fullname" . }}-cephfs-nodeplugin-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-nfs-ctrlplugin-scc
  labels:
    {{- include "ceph-csi-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ceph-csi-operator.fullname" . }}-scc-user
subjects:
  - kind: ServiceAccount
    name: {{ include "ceph-csi-operator.fullname" . }}-nfs-ctrlplugin-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-nfs-nodeplugin-scc
  labels:
    {{- include "ceph-csi-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ceph-csi-operator.fullname" . }}-scc-user
subjects:
  - kind: ServiceAccount
    name: {{ include "ceph-csi-operator.fullname" . }}-nfs-nodeplugin-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-nvmeof-ctrlplugin-scc
  labels:
    {{- include "ceph-csi-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ceph-csi-operator.fullname" . }}-scc-user
subjects:
  - kind: ServiceAccount
    name: {{ include "ceph-csi-operator.fullname" . }}-nvmeof-ctrlplugin-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-nvmeof-nodeplugin-scc
  labels:
    {{- include "ceph-csi-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ceph-csi-operator.fullname" . }}-scc-user
subjects:
  - kind: ServiceAccount
    name: {{ include "ceph-csi-operator.fullname" . }}-nvmeof-nodeplugin-sa
    namespace: {{ .Release.Namespace }}
{{- end }}
