{{- $root := . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-controller-manager
  namespace: {{ $root.Release.Namespace }}
  labels:
  {{- include "ceph-csi-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . | indent 2 }}
{{- end }}
