//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephConnection) DeepCopyInto(out *CephConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephConnection.
func (in *CephConnection) DeepCopy() *CephConnection {
	if in == nil {
		return nil
	}
	out := new(CephConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephConnectionList) DeepCopyInto(out *CephConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CephConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephConnectionList.
func (in *CephConnectionList) DeepCopy() *CephConnectionList {
	if in == nil {
		return nil
	}
	out := new(CephConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephConnectionSpec) DeepCopyInto(out *CephConnectionSpec) {
	*out = *in
	if in.Monitors != nil {
		in, out := &in.Monitors, &out.Monitors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReadAffinity != nil {
		in, out := &in.ReadAffinity, &out.ReadAffinity
		*out = new(ReadAffinitySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephConnectionSpec.
func (in *CephConnectionSpec) DeepCopy() *CephConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(CephConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephConnectionStatus) DeepCopyInto(out *CephConnectionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephConnectionStatus.
func (in *CephConnectionStatus) DeepCopy() *CephConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(CephConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephFsConfigSpec) DeepCopyInto(out *CephFsConfigSpec) {
	*out = *in
	if in.KernelMountOptions != nil {
		in, out := &in.KernelMountOptions, &out.KernelMountOptions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FuseMountOptions != nil {
		in, out := &in.FuseMountOptions, &out.FuseMountOptions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RadosNamespace != nil {
		in, out := &in.RadosNamespace, &out.RadosNamespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephFsConfigSpec.
func (in *CephFsConfigSpec) DeepCopy() *CephFsConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CephFsConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientProfile) DeepCopyInto(out *ClientProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientProfile.
func (in *ClientProfile) DeepCopy() *ClientProfile {
	if in == nil {
		return nil
	}
	out := new(ClientProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClientProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientProfileList) DeepCopyInto(out *ClientProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClientProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientProfileList.
func (in *ClientProfileList) DeepCopy() *ClientProfileList {
	if in == nil {
		return nil
	}
	out := new(ClientProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClientProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientProfileSpec) DeepCopyInto(out *ClientProfileSpec) {
	*out = *in
	out.CephConnectionRef = in.CephConnectionRef
	if in.CephFs != nil {
		in, out := &in.CephFs, &out.CephFs
		*out = new(CephFsConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Rbd != nil {
		in, out := &in.Rbd, &out.Rbd
		*out = new(RbdConfigSpec)
		**out = **in
	}
	if in.Nfs != nil {
		in, out := &in.Nfs, &out.Nfs
		*out = new(NfsConfigSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientProfileSpec.
func (in *ClientProfileSpec) DeepCopy() *ClientProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ClientProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientProfileStatus) DeepCopyInto(out *ClientProfileStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientProfileStatus.
func (in *ClientProfileStatus) DeepCopy() *ClientProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ClientProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NfsConfigSpec) DeepCopyInto(out *NfsConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NfsConfigSpec.
func (in *NfsConfigSpec) DeepCopy() *NfsConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NfsConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbdConfigSpec) DeepCopyInto(out *RbdConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbdConfigSpec.
func (in *RbdConfigSpec) DeepCopy() *RbdConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RbdConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadAffinitySpec) DeepCopyInto(out *ReadAffinitySpec) {
	*out = *in
	if in.CrushLocationLabels != nil {
		in, out := &in.CrushLocationLabels, &out.CrushLocationLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadAffinitySpec.
func (in *ReadAffinitySpec) DeepCopy() *ReadAffinitySpec {
	if in == nil {
		return nil
	}
	out := new(ReadAffinitySpec)
	in.DeepCopyInto(out)
	return out
}
