name: test-charts

on:
  pull_request:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'docs/**' # ignore all the documents
      - '*.md' # Ignore the Readme and PendingReleaseNote file
      - '.*' # Ignore the config files

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  run-e2e-tests:
    name: ${{ matrix.driver }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        driver:
          - cephfs
          - rbd
          - nfs
          - nvmeof
    steps:

      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Deploy helm charts
        uses: ./.github/actions/deploy-charts
        with:
          driverType: ${{ matrix.driver }}
          valuesFile: ./test/scripts/k8s-storage/helm/values-${{ matrix.driver }}.yaml

      - name: Run E2E tests
        uses: ./.github/actions/run-e2e-tests
        with:
          driverType: ${{ matrix.driver }}
          logPrefix: helm
