---
name: Verify Documentation

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  verify-docs-nav:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Verify documentation navigation
        run: make verify-docs-nav
